// <auto-generated />
using System;
using BlunderYears.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlunderYears.Data.EF.Migrations.Migrations
{
    [DbContext(typeof(BlunderYearsContext))]
    [Migration("20240411021758_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blunderyears")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.AlbumTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Album", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.SyncServices.Dropbox.DropboxFileTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char");

                    b.Property<string>("DropboxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("DropboxRegistrationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("PhotoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DropboxRegistrationId");

                    b.HasIndex("PhotoId");

                    b.ToTable("DropboxFileTable", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.SyncServices.Dropbox.DropboxRegistrationTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("AlbumTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumTableId");

                    b.ToTable("DropboxRegistration", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.AgeTypeTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AgeType", "blunderyears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hours"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Days"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Weeks"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Months"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Years"
                        });
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.ExifTypeTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exif", "blunderyears");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "PropertyTagGpsVer"
                        },
                        new
                        {
                            Id = 1,
                            Description = "PropertyTagGpsLatitudeRef"
                        },
                        new
                        {
                            Id = 2,
                            Description = "PropertyTagGpsLatitude"
                        },
                        new
                        {
                            Id = 3,
                            Description = "PropertyTagGpsLongitudeRef"
                        },
                        new
                        {
                            Id = 4,
                            Description = "PropertyTagGpsLongitude"
                        },
                        new
                        {
                            Id = 5,
                            Description = "PropertyTagGpsAltitudeRef"
                        },
                        new
                        {
                            Id = 6,
                            Description = "PropertyTagGpsAltitude"
                        },
                        new
                        {
                            Id = 7,
                            Description = "PropertyTagGpsGpsTime"
                        },
                        new
                        {
                            Id = 8,
                            Description = "PropertyTagGpsGpsSatellites"
                        },
                        new
                        {
                            Id = 9,
                            Description = "PropertyTagGpsGpsStatus"
                        },
                        new
                        {
                            Id = 10,
                            Description = "PropertyTagGpsGpsMeasureMode"
                        },
                        new
                        {
                            Id = 11,
                            Description = "PropertyTagGpsGpsDop"
                        },
                        new
                        {
                            Id = 12,
                            Description = "PropertyTagGpsSpeedRef"
                        },
                        new
                        {
                            Id = 13,
                            Description = "PropertyTagGpsSpeed"
                        },
                        new
                        {
                            Id = 14,
                            Description = "PropertyTagGpsTrackRef"
                        },
                        new
                        {
                            Id = 15,
                            Description = "PropertyTagGpsTrack"
                        },
                        new
                        {
                            Id = 16,
                            Description = "PropertyTagGpsImgDirRef"
                        },
                        new
                        {
                            Id = 17,
                            Description = "PropertyTagGpsImgDir"
                        },
                        new
                        {
                            Id = 18,
                            Description = "PropertyTagGpsMapDatum"
                        },
                        new
                        {
                            Id = 19,
                            Description = "PropertyTagGpsDestLatRef"
                        },
                        new
                        {
                            Id = 20,
                            Description = "PropertyTagGpsDestLat"
                        },
                        new
                        {
                            Id = 21,
                            Description = "PropertyTagGpsDestLongRef"
                        },
                        new
                        {
                            Id = 22,
                            Description = "PropertyTagGpsDestLong"
                        },
                        new
                        {
                            Id = 23,
                            Description = "PropertyTagGpsDestBearRef"
                        },
                        new
                        {
                            Id = 24,
                            Description = "PropertyTagGpsDestBear"
                        },
                        new
                        {
                            Id = 25,
                            Description = "PropertyTagGpsDestDistRef"
                        },
                        new
                        {
                            Id = 26,
                            Description = "PropertyTagGpsDestDist"
                        },
                        new
                        {
                            Id = 254,
                            Description = "PropertyTagNewSubfileType"
                        },
                        new
                        {
                            Id = 255,
                            Description = "PropertyTagSubfileType"
                        },
                        new
                        {
                            Id = 256,
                            Description = "PropertyTagImageWidth"
                        },
                        new
                        {
                            Id = 257,
                            Description = "PropertyTagImageHeight"
                        },
                        new
                        {
                            Id = 258,
                            Description = "PropertyTagBitsPerSample"
                        },
                        new
                        {
                            Id = 259,
                            Description = "PropertyTagCompression"
                        },
                        new
                        {
                            Id = 262,
                            Description = "PropertyTagPhotometricInterp"
                        },
                        new
                        {
                            Id = 263,
                            Description = "PropertyTagThreshHolding"
                        },
                        new
                        {
                            Id = 264,
                            Description = "PropertyTagCellWidth"
                        },
                        new
                        {
                            Id = 265,
                            Description = "PropertyTagCellHeight"
                        },
                        new
                        {
                            Id = 266,
                            Description = "PropertyTagFillOrder"
                        },
                        new
                        {
                            Id = 269,
                            Description = "PropertyTagDocumentName"
                        },
                        new
                        {
                            Id = 270,
                            Description = "PropertyTagImageDescription"
                        },
                        new
                        {
                            Id = 271,
                            Description = "PropertyTagEquipMake"
                        },
                        new
                        {
                            Id = 272,
                            Description = "PropertyTagEquipModel"
                        },
                        new
                        {
                            Id = 273,
                            Description = "PropertyTagStripOffsets"
                        },
                        new
                        {
                            Id = 274,
                            Description = "PropertyTagOrientation"
                        },
                        new
                        {
                            Id = 277,
                            Description = "PropertyTagSamplesPerPixel"
                        },
                        new
                        {
                            Id = 278,
                            Description = "PropertyTagRowsPerStrip"
                        },
                        new
                        {
                            Id = 279,
                            Description = "PropertyTagStripBytesCount"
                        },
                        new
                        {
                            Id = 280,
                            Description = "PropertyTagMinSampleValue"
                        },
                        new
                        {
                            Id = 281,
                            Description = "PropertyTagMaxSampleValue"
                        },
                        new
                        {
                            Id = 282,
                            Description = "PropertyTagXResolution"
                        },
                        new
                        {
                            Id = 283,
                            Description = "PropertyTagYResolution"
                        },
                        new
                        {
                            Id = 284,
                            Description = "PropertyTagPlanarConfig"
                        },
                        new
                        {
                            Id = 285,
                            Description = "PropertyTagPageName"
                        },
                        new
                        {
                            Id = 286,
                            Description = "PropertyTagXPosition"
                        },
                        new
                        {
                            Id = 287,
                            Description = "PropertyTagYPosition"
                        },
                        new
                        {
                            Id = 288,
                            Description = "PropertyTagFreeOffset"
                        },
                        new
                        {
                            Id = 289,
                            Description = "PropertyTagFreeByteCounts"
                        },
                        new
                        {
                            Id = 290,
                            Description = "PropertyTagGrayResponseUnit"
                        },
                        new
                        {
                            Id = 291,
                            Description = "PropertyTagGrayResponseCurve"
                        },
                        new
                        {
                            Id = 292,
                            Description = "PropertyTagT4Option"
                        },
                        new
                        {
                            Id = 293,
                            Description = "PropertyTagT6Option"
                        },
                        new
                        {
                            Id = 296,
                            Description = "PropertyTagResolutionUnit"
                        },
                        new
                        {
                            Id = 297,
                            Description = "PropertyTagPageNumber"
                        },
                        new
                        {
                            Id = 301,
                            Description = "PropertyTagTransferFunction"
                        },
                        new
                        {
                            Id = 305,
                            Description = "PropertyTagSoftwareUsed"
                        },
                        new
                        {
                            Id = 306,
                            Description = "PropertyTagDateTime"
                        },
                        new
                        {
                            Id = 315,
                            Description = "PropertyTagArtist"
                        },
                        new
                        {
                            Id = 316,
                            Description = "PropertyTagHostComputer"
                        },
                        new
                        {
                            Id = 317,
                            Description = "PropertyTagPredictor"
                        },
                        new
                        {
                            Id = 318,
                            Description = "PropertyTagWhitePoint"
                        },
                        new
                        {
                            Id = 319,
                            Description = "PropertyTagPrimaryChromaticities"
                        },
                        new
                        {
                            Id = 320,
                            Description = "PropertyTagColorMap"
                        },
                        new
                        {
                            Id = 321,
                            Description = "PropertyTagHalftoneHints"
                        },
                        new
                        {
                            Id = 322,
                            Description = "PropertyTagTileWidth"
                        },
                        new
                        {
                            Id = 323,
                            Description = "PropertyTagTileLength"
                        },
                        new
                        {
                            Id = 324,
                            Description = "PropertyTagTileOffset"
                        },
                        new
                        {
                            Id = 325,
                            Description = "PropertyTagTileByteCounts"
                        },
                        new
                        {
                            Id = 332,
                            Description = "PropertyTagInkSet"
                        },
                        new
                        {
                            Id = 333,
                            Description = "PropertyTagInkNames"
                        },
                        new
                        {
                            Id = 334,
                            Description = "PropertyTagNumberOfInks"
                        },
                        new
                        {
                            Id = 336,
                            Description = "PropertyTagDotRange"
                        },
                        new
                        {
                            Id = 337,
                            Description = "PropertyTagTargetPrinter"
                        },
                        new
                        {
                            Id = 338,
                            Description = "PropertyTagExtraSamples"
                        },
                        new
                        {
                            Id = 339,
                            Description = "PropertyTagSampleFormat"
                        },
                        new
                        {
                            Id = 340,
                            Description = "PropertyTagSMinSampleValue"
                        },
                        new
                        {
                            Id = 341,
                            Description = "PropertyTagSMaxSampleValue"
                        },
                        new
                        {
                            Id = 342,
                            Description = "PropertyTagTransferRange"
                        },
                        new
                        {
                            Id = 512,
                            Description = "PropertyTagJPEGProc"
                        },
                        new
                        {
                            Id = 513,
                            Description = "PropertyTagJPEGInterFormat"
                        },
                        new
                        {
                            Id = 514,
                            Description = "PropertyTagJPEGInterLength"
                        },
                        new
                        {
                            Id = 515,
                            Description = "PropertyTagJPEGRestartInterval"
                        },
                        new
                        {
                            Id = 517,
                            Description = "PropertyTagJPEGLosslessPredictors"
                        },
                        new
                        {
                            Id = 518,
                            Description = "PropertyTagJPEGPointTransforms"
                        },
                        new
                        {
                            Id = 519,
                            Description = "PropertyTagJPEGQTables"
                        },
                        new
                        {
                            Id = 520,
                            Description = "PropertyTagJPEGDCTables"
                        },
                        new
                        {
                            Id = 521,
                            Description = "PropertyTagJPEGACTables"
                        },
                        new
                        {
                            Id = 529,
                            Description = "PropertyTagYCbCrCoefficients"
                        },
                        new
                        {
                            Id = 530,
                            Description = "PropertyTagYCbCrSubsampling"
                        },
                        new
                        {
                            Id = 531,
                            Description = "PropertyTagYCbCrPositioning"
                        },
                        new
                        {
                            Id = 532,
                            Description = "PropertyTagREFBlackWhite"
                        },
                        new
                        {
                            Id = 769,
                            Description = "PropertyTagGamma"
                        },
                        new
                        {
                            Id = 770,
                            Description = "PropertyTagICCProfileDescriptor"
                        },
                        new
                        {
                            Id = 771,
                            Description = "PropertyTagSRGBRenderingIntent"
                        },
                        new
                        {
                            Id = 800,
                            Description = "PropertyTagImageTitle"
                        },
                        new
                        {
                            Id = 20481,
                            Description = "PropertyTagResolutionXUnit"
                        },
                        new
                        {
                            Id = 20482,
                            Description = "PropertyTagResolutionYUnit"
                        },
                        new
                        {
                            Id = 20483,
                            Description = "PropertyTagResolutionXLengthUnit"
                        },
                        new
                        {
                            Id = 20484,
                            Description = "PropertyTagResolutionYLengthUnit"
                        },
                        new
                        {
                            Id = 20485,
                            Description = "PropertyTagPrintFlags"
                        },
                        new
                        {
                            Id = 20486,
                            Description = "PropertyTagPrintFlagsVersion"
                        },
                        new
                        {
                            Id = 20487,
                            Description = "PropertyTagPrintFlagsCrop"
                        },
                        new
                        {
                            Id = 20488,
                            Description = "PropertyTagPrintFlagsBleedWidth"
                        },
                        new
                        {
                            Id = 20489,
                            Description = "PropertyTagPrintFlagsBleedWidthScale"
                        },
                        new
                        {
                            Id = 20490,
                            Description = "PropertyTagHalftoneLPI"
                        },
                        new
                        {
                            Id = 20491,
                            Description = "PropertyTagHalftoneLPIUnit"
                        },
                        new
                        {
                            Id = 20492,
                            Description = "PropertyTagHalftoneDegree"
                        },
                        new
                        {
                            Id = 20493,
                            Description = "PropertyTagHalftoneShape"
                        },
                        new
                        {
                            Id = 20494,
                            Description = "PropertyTagHalftoneMisc"
                        },
                        new
                        {
                            Id = 20495,
                            Description = "PropertyTagHalftoneScreen"
                        },
                        new
                        {
                            Id = 20496,
                            Description = "PropertyTagJPEGQuality"
                        },
                        new
                        {
                            Id = 20497,
                            Description = "PropertyTagGridSize"
                        },
                        new
                        {
                            Id = 20498,
                            Description = "PropertyTagThumbnailFormat"
                        },
                        new
                        {
                            Id = 20499,
                            Description = "PropertyTagThumbnailWidth"
                        },
                        new
                        {
                            Id = 20500,
                            Description = "PropertyTagThumbnailHeight"
                        },
                        new
                        {
                            Id = 20501,
                            Description = "PropertyTagThumbnailColorDepth"
                        },
                        new
                        {
                            Id = 20502,
                            Description = "PropertyTagThumbnailPlanes"
                        },
                        new
                        {
                            Id = 20503,
                            Description = "PropertyTagThumbnailRawBytes"
                        },
                        new
                        {
                            Id = 20504,
                            Description = "PropertyTagThumbnailSize"
                        },
                        new
                        {
                            Id = 20505,
                            Description = "PropertyTagThumbnailCompressedSize"
                        },
                        new
                        {
                            Id = 20506,
                            Description = "PropertyTagColorTransferFunction"
                        },
                        new
                        {
                            Id = 20507,
                            Description = "PropertyTagThumbnailData"
                        },
                        new
                        {
                            Id = 20512,
                            Description = "PropertyTagThumbnailImageWidth"
                        },
                        new
                        {
                            Id = 20513,
                            Description = "PropertyTagThumbnailImageHeight"
                        },
                        new
                        {
                            Id = 20514,
                            Description = "PropertyTagThumbnailBitsPerSample"
                        },
                        new
                        {
                            Id = 20515,
                            Description = "PropertyTagThumbnailCompression"
                        },
                        new
                        {
                            Id = 20516,
                            Description = "PropertyTagThumbnailPhotometricInterp"
                        },
                        new
                        {
                            Id = 20517,
                            Description = "PropertyTagThumbnailImageDescription"
                        },
                        new
                        {
                            Id = 20518,
                            Description = "PropertyTagThumbnailEquipMake"
                        },
                        new
                        {
                            Id = 20519,
                            Description = "PropertyTagThumbnailEquipModel"
                        },
                        new
                        {
                            Id = 20520,
                            Description = "PropertyTagThumbnailStripOffsets"
                        },
                        new
                        {
                            Id = 20521,
                            Description = "PropertyTagThumbnailOrientation"
                        },
                        new
                        {
                            Id = 20522,
                            Description = "PropertyTagThumbnailSamplesPerPixel"
                        },
                        new
                        {
                            Id = 20523,
                            Description = "PropertyTagThumbnailRowsPerStrip"
                        },
                        new
                        {
                            Id = 20524,
                            Description = "PropertyTagThumbnailStripBytesCount"
                        },
                        new
                        {
                            Id = 20525,
                            Description = "PropertyTagThumbnailResolutionX"
                        },
                        new
                        {
                            Id = 20526,
                            Description = "PropertyTagThumbnailResolutionY"
                        },
                        new
                        {
                            Id = 20527,
                            Description = "PropertyTagThumbnailPlanarConfig"
                        },
                        new
                        {
                            Id = 20528,
                            Description = "PropertyTagThumbnailResolutionUnit"
                        },
                        new
                        {
                            Id = 20529,
                            Description = "PropertyTagThumbnailTransferFunction"
                        },
                        new
                        {
                            Id = 20530,
                            Description = "PropertyTagThumbnailSoftwareUsed"
                        },
                        new
                        {
                            Id = 20531,
                            Description = "PropertyTagThumbnailDateTime"
                        },
                        new
                        {
                            Id = 20532,
                            Description = "PropertyTagThumbnailArtist"
                        },
                        new
                        {
                            Id = 20533,
                            Description = "PropertyTagThumbnailWhitePoint"
                        },
                        new
                        {
                            Id = 20534,
                            Description = "PropertyTagThumbnailPrimaryChromaticities"
                        },
                        new
                        {
                            Id = 20535,
                            Description = "PropertyTagThumbnailYCbCrCoefficients"
                        },
                        new
                        {
                            Id = 20536,
                            Description = "PropertyTagThumbnailYCbCrSubsampling"
                        },
                        new
                        {
                            Id = 20537,
                            Description = "PropertyTagThumbnailYCbCrPositioning"
                        },
                        new
                        {
                            Id = 20538,
                            Description = "PropertyTagThumbnailRefBlackWhite"
                        },
                        new
                        {
                            Id = 20539,
                            Description = "PropertyTagThumbnailCopyRight"
                        },
                        new
                        {
                            Id = 20624,
                            Description = "PropertyTagLuminanceTable"
                        },
                        new
                        {
                            Id = 20625,
                            Description = "PropertyTagChrominanceTable"
                        },
                        new
                        {
                            Id = 20736,
                            Description = "PropertyTagFrameDelay"
                        },
                        new
                        {
                            Id = 20737,
                            Description = "PropertyTagLoopCount"
                        },
                        new
                        {
                            Id = 20738,
                            Description = "PropertyTagGlobalPalette"
                        },
                        new
                        {
                            Id = 20739,
                            Description = "PropertyTagIndexBackground"
                        },
                        new
                        {
                            Id = 20740,
                            Description = "PropertyTagIndexTransparent"
                        },
                        new
                        {
                            Id = 20752,
                            Description = "PropertyTagPixelUnit"
                        },
                        new
                        {
                            Id = 20753,
                            Description = "PropertyTagPixelPerUnitX"
                        },
                        new
                        {
                            Id = 20754,
                            Description = "PropertyTagPixelPerUnitY"
                        },
                        new
                        {
                            Id = 20755,
                            Description = "PropertyTagPaletteHistogram"
                        },
                        new
                        {
                            Id = 33432,
                            Description = "PropertyTagCopyright"
                        },
                        new
                        {
                            Id = 33434,
                            Description = "PropertyTagExifExposureTime"
                        },
                        new
                        {
                            Id = 33437,
                            Description = "PropertyTagExifFNumber"
                        },
                        new
                        {
                            Id = 34665,
                            Description = "PropertyTagExifIFD"
                        },
                        new
                        {
                            Id = 34675,
                            Description = "PropertyTagICCProfile"
                        },
                        new
                        {
                            Id = 34850,
                            Description = "PropertyTagExifExposureProg"
                        },
                        new
                        {
                            Id = 34852,
                            Description = "PropertyTagExifSpectralSense"
                        },
                        new
                        {
                            Id = 34853,
                            Description = "PropertyTagGpsIFD"
                        },
                        new
                        {
                            Id = 34855,
                            Description = "PropertyTagExifISOSpeed"
                        },
                        new
                        {
                            Id = 34856,
                            Description = "PropertyTagExifOECF"
                        },
                        new
                        {
                            Id = 36864,
                            Description = "PropertyTagExifVer"
                        },
                        new
                        {
                            Id = 36867,
                            Description = "PropertyTagExifDTOrig"
                        },
                        new
                        {
                            Id = 36868,
                            Description = "PropertyTagExifDTDigitized"
                        },
                        new
                        {
                            Id = 37121,
                            Description = "PropertyTagExifCompConfig"
                        },
                        new
                        {
                            Id = 37122,
                            Description = "PropertyTagExifCompBPP"
                        },
                        new
                        {
                            Id = 37377,
                            Description = "PropertyTagExifShutterSpeed"
                        },
                        new
                        {
                            Id = 37378,
                            Description = "PropertyTagExifAperture"
                        },
                        new
                        {
                            Id = 37379,
                            Description = "PropertyTagExifBrightness"
                        },
                        new
                        {
                            Id = 37380,
                            Description = "PropertyTagExifExposureBias"
                        },
                        new
                        {
                            Id = 37381,
                            Description = "PropertyTagExifMaxAperture"
                        },
                        new
                        {
                            Id = 37382,
                            Description = "PropertyTagExifSubjectDist"
                        },
                        new
                        {
                            Id = 37383,
                            Description = "PropertyTagExifMeteringMode"
                        },
                        new
                        {
                            Id = 37384,
                            Description = "PropertyTagExifLightSource"
                        },
                        new
                        {
                            Id = 37385,
                            Description = "PropertyTagExifFlash"
                        },
                        new
                        {
                            Id = 37386,
                            Description = "PropertyTagExifFocalLength"
                        },
                        new
                        {
                            Id = 37500,
                            Description = "PropertyTagExifMakerNote"
                        },
                        new
                        {
                            Id = 37510,
                            Description = "PropertyTagExifUserComment"
                        },
                        new
                        {
                            Id = 37520,
                            Description = "PropertyTagExifDTSubsec"
                        },
                        new
                        {
                            Id = 37521,
                            Description = "PropertyTagExifDTOrigSS"
                        },
                        new
                        {
                            Id = 37522,
                            Description = "PropertyTagExifDTDigSS"
                        },
                        new
                        {
                            Id = 40960,
                            Description = "PropertyTagExifFPXVer"
                        },
                        new
                        {
                            Id = 40961,
                            Description = "PropertyTagExifColorSpace"
                        },
                        new
                        {
                            Id = 40962,
                            Description = "PropertyTagExifPixXDim"
                        },
                        new
                        {
                            Id = 40963,
                            Description = "PropertyTagExifPixYDim"
                        },
                        new
                        {
                            Id = 40964,
                            Description = "PropertyTagExifRelatedWav"
                        },
                        new
                        {
                            Id = 40965,
                            Description = "PropertyTagExifInterop"
                        },
                        new
                        {
                            Id = 41483,
                            Description = "PropertyTagExifFlashEnergy"
                        },
                        new
                        {
                            Id = 41484,
                            Description = "PropertyTagExifSpatialFR"
                        },
                        new
                        {
                            Id = 41486,
                            Description = "PropertyTagExifFocalXRes"
                        },
                        new
                        {
                            Id = 41487,
                            Description = "PropertyTagExifFocalYRes"
                        },
                        new
                        {
                            Id = 41488,
                            Description = "PropertyTagExifFocalResUnit"
                        },
                        new
                        {
                            Id = 41492,
                            Description = "PropertyTagExifSubjectLoc"
                        },
                        new
                        {
                            Id = 41493,
                            Description = "PropertyTagExifExposureIndex"
                        },
                        new
                        {
                            Id = 41495,
                            Description = "PropertyTagExifSensingMethod"
                        },
                        new
                        {
                            Id = 41728,
                            Description = "PropertyTagExifFileSource"
                        },
                        new
                        {
                            Id = 41729,
                            Description = "PropertyTagExifSceneType"
                        },
                        new
                        {
                            Id = 41730,
                            Description = "PropertyTagExifCfaPattern"
                        });
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.PhotoExifTable", b =>
                {
                    b.Property<long>("PhotoId")
                        .HasColumnType("bigint");

                    b.Property<int>("ExifTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("PhotoId", "ExifTypeId");

                    b.HasIndex("ExifTypeId");

                    b.ToTable("PhotoExif", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.PhotoTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgeTypeId")
                        .HasColumnType("int");

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char");

                    b.Property<DateTime>("PhotoDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgeTypeId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ContentHash");

                    b.ToTable("Photo", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.UserFamilyPermissionsTable", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FamilyId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("UserFamilyPermissions", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.FamilyPermissionsTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FamilyPermissions", "blunderyears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Owner"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Partner"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Contributor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Reader"
                        });
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.FamilyTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UserAlbumPermissions", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserDetailsTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FamilyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserEmailTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEmail", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("FamilyTableId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTableId");

                    b.ToTable("User", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserTokenTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Idp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Nonce")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sub")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UserDetailsTableId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserDetailsTableId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserToken", "blunderyears");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.AlbumTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Users.UserTable", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlunderYears.Data.Models.Users.FamilyTable", "Family")
                        .WithMany("Albums")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.SyncServices.Dropbox.DropboxFileTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Photos.Albums.SyncServices.Dropbox.DropboxRegistrationTable", "DropboxRegistration")
                        .WithMany("Files")
                        .HasForeignKey("DropboxRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlunderYears.Data.Models.Photos.Photos.PhotoTable", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DropboxRegistration");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.SyncServices.Dropbox.DropboxRegistrationTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Photos.Albums.AlbumTable", null)
                        .WithMany("DropboxRegistrations")
                        .HasForeignKey("AlbumTableId");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.PhotoExifTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Photos.Photos.ExifTypeTable", "ExifType")
                        .WithMany()
                        .HasForeignKey("ExifTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlunderYears.Data.Models.Photos.Photos.PhotoTable", "Photo")
                        .WithMany("ExifData")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExifType");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.PhotoTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Photos.Photos.AgeTypeTable", "AgeType")
                        .WithMany()
                        .HasForeignKey("AgeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlunderYears.Data.Models.Photos.Albums.AlbumTable", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeType");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.UserFamilyPermissionsTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Users.FamilyTable", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlunderYears.Data.Models.Users.FamilyPermissionsTable", "Permissions")
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlunderYears.Data.Models.Users.UserTable", "User")
                        .WithMany("Families")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Permissions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserDetailsTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Users.UserTable", "User")
                        .WithOne("Details")
                        .HasForeignKey("BlunderYears.Data.Models.Users.UserDetailsTable", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserEmailTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Users.UserTable", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Users.FamilyTable", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyTableId");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserTokenTable", b =>
                {
                    b.HasOne("BlunderYears.Data.Models.Users.UserDetailsTable", null)
                        .WithMany("Emails")
                        .HasForeignKey("UserDetailsTableId");

                    b.HasOne("BlunderYears.Data.Models.Users.UserTable", "User")
                        .WithOne("Token")
                        .HasForeignKey("BlunderYears.Data.Models.Users.UserTokenTable", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.AlbumTable", b =>
                {
                    b.Navigation("DropboxRegistrations");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Albums.SyncServices.Dropbox.DropboxRegistrationTable", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Photos.Photos.PhotoTable", b =>
                {
                    b.Navigation("ExifData");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.FamilyTable", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserDetailsTable", b =>
                {
                    b.Navigation("Emails");
                });

            modelBuilder.Entity("BlunderYears.Data.Models.Users.UserTable", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Families");

                    b.Navigation("Token")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
