name: Build and deploy dotnet core project to Azure Function App - blunderyears

on:
  push:
    branches:
      - main
    paths:
      - 'src/BlunderYears'
      - '.github/workflows/main_blunderyears.yml'
  workflow_dispatch:

env:
  SOLUTION_FOLDER: 'src/BlunderYears'
  PROJECT_NAME: 'BlunderYears.API'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './output'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: 'Unit Test'
        shell: bash
        run: |
          pushd './${{ env.SOLUTION_FOLDER }}'
          dotnet test --configuration Release
          popd

      - name: 'Build'
        shell: bash
        run: |
          pushd './${{ env.SOLUTION_FOLDER }}/${{ env.PROJECT_NAME }}'
          dotnet build --configuration Release --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'blunderyears'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_40B158A4E6D5432BACA19466D51E55E4 }}
          